# Generated by Django 5.0.1 on 2025-12-16 05:19

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolOnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('school_type', models.CharField(blank=True, choices=[], max_length=20)),
                ('configuration', models.JSONField(help_text='Template configuration JSON')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schools_template',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, help_text='Optional. 150 characters or fewer.', max_length=150, null=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='core.school')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OpenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True, help_text='Required qualifications and experience')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'db_table': 'users_open_position',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role display name', max_length=100)),
                ('category', models.CharField(choices=[('administration', 'Administration'), ('academic', 'Academic'), ('student', 'Student'), ('parent', 'Parent'), ('support', 'Support Staff')], max_length=50)),
                ('permissions', models.JSONField(default=list, help_text='List of permission strings')),
                ('is_system_role', models.BooleanField(default=False)),
                ('system_role_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Role description and responsibilities')),
                ('can_manage_roles', models.BooleanField(default=False, help_text='Can create/edit roles')),
                ('can_manage_staff', models.BooleanField(default=False, help_text='Can manage staff members')),
                ('can_manage_students', models.BooleanField(default=False, help_text='Can manage students')),
                ('can_manage_academics', models.BooleanField(default=False, help_text='Can manage academic records')),
                ('can_manage_finances', models.BooleanField(default=False, help_text='Can manage financial records')),
                ('can_view_reports', models.BooleanField(default=False, help_text='Can view reports')),
                ('can_communicate', models.BooleanField(default=False, help_text='Can send communications')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'db_table': 'users_role',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.role')),
            ],
            options={
                'db_table': 'users_profile',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scholarship_type', models.CharField(choices=[('merit', 'Merit-Based'), ('need', 'Need-Based'), ('sports', 'Sports'), ('arts', 'Arts'), ('staff', 'Staff Discount'), ('external', 'External Sponsorship')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount on fees', max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount discount (alternative to percentage)', max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount', max_digits=10, null=True)),
                ('eligibility_criteria', models.JSONField(blank=True, default=list)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('total_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('slots_taken', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('application_start', models.DateField(blank=True, null=True)),
                ('application_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'db_table': 'schools_scholarship',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, help_text='Staff identification number', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], help_text='Marital status', max_length=20)),
                ('nationality', models.CharField(blank=True, default='Nigerian', max_length=100)),
                ('state_of_origin', models.CharField(blank=True, max_length=100)),
                ('lga_of_origin', models.CharField(blank=True, help_text='Local Government Area', max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('volunteer', 'Volunteer'), ('temporary', 'Temporary')], default='full_time', max_length=20)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('position', models.CharField(help_text='Job title/position', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Department/Section', max_length=100)),
                ('qualification', models.CharField(blank=True, help_text='Highest qualification (e.g., B.Sc, M.Ed, PhD)', max_length=100)),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization', max_length=200)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Years of teaching/professional experience')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, help_text='Alternate phone number', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('tax_identification_number', models.CharField(blank=True, max_length=20)),
                ('insurance_number', models.CharField(blank=True, help_text='NHIS or other insurance', max_length=50)),
                ('qualifications', models.JSONField(blank=True, default=list, help_text='List of qualifications with details')),
                ('is_active', models.BooleanField(default=True)),
                ('is_teaching_staff', models.BooleanField(default=True, help_text='Whether this staff teaches classes')),
                ('is_management', models.BooleanField(default=False, help_text='Part of school management team')),
                ('next_of_kin', models.TextField(blank=True, help_text='Next of kin details')),
                ('medical_information', models.TextField(blank=True, help_text='Medical conditions or allergies')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_review_date', models.DateField(blank=True, help_text='Last performance review', null=True)),
                ('next_review_date', models.DateField(blank=True, help_text='Next performance review', null=True)),
                ('assigned_classes', models.ManyToManyField(blank=True, help_text='Academic classes this staff member is assigned to', related_name='assigned_staff', to='core.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Subjects this staff member teaches', related_name='teaching_staff', to='core.subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
                'db_table': 'users_staff',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
            options={
                'db_table': 'users_staff_assignment',
            },
        ),
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'db_table': 'users_staff_invitation',
            },
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('application_type', models.CharField(choices=[('new_teacher', 'New Teacher (No Experience)'), ('experienced', 'Experienced Teacher'), ('transfer', 'Transfer from Another School')], default='experienced', max_length=20)),
                ('position_applied', models.CharField(help_text='Position being applied for', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('qualification', models.CharField(help_text='Highest qualification', max_length=100)),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization', max_length=200)),
                ('cover_letter', models.TextField(blank=True, help_text='Why you want to join this school')),
                ('resume', models.FileField(blank=True, null=True, upload_to='teacher_resumes/')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='teacher_certificates/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.openposition')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_teacher_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='auth_user_phone_n_baf3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='openposition',
            index=models.Index(fields=['school', 'is_active'], name='users_open__school__6a2961_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['school', 'is_system_role'], name='users_role_school__9851af_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['school', 'category'], name='users_role_school__e08c0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'school'], name='users_profi_user_id_5b545f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'school')},
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['school', 'is_active'], name='schools_sch_school__ac75ca_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['scholarship_type'], name='schools_sch_scholar_f612dc_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['school', 'is_active'], name='users_staff_school__ccd913_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['school', 'department'], name='users_staff_school__a27c27_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['school', 'position'], name='users_staff_school__7270c4_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_id'], name='users_staff_staff_i_04dceb_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['email'], name='users_staff_email_442bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['date_joined'], name='users_staff_date_jo_00d4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_teaching_staff'], name='users_staff_is_teac_3c8934_idx'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['staff', 'is_active'], name='users_staff_staff_i_1f7e4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffassignment',
            unique_together={('staff', 'role')},
        ),
        migrations.AddIndex(
            model_name='staffinvitation',
            index=models.Index(fields=['token', 'status'], name='users_staff_token_c27d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='staffinvitation',
            index=models.Index(fields=['school', 'status'], name='users_staff_school__8421d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffinvitation',
            unique_together={('school', 'email')},
        ),
        migrations.AddIndex(
            model_name='teacherapplication',
            index=models.Index(fields=['school', 'status'], name='users_teach_school__0d6cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherapplication',
            index=models.Index(fields=['email', 'status'], name='users_teach_email_13bdf8_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherapplication',
            index=models.Index(fields=['created_at'], name='users_teach_created_1ef972_idx'),
        ),
    ]
