# Generated by Django 5.0.1 on 2025-11-22 08:16

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolOnboardingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=100)),
                ('school_type', models.CharField(choices=[('nursery', 'Nursery Only'), ('primary', 'Primary Only'), ('secondary', 'Secondary Only'), ('combined', 'Nursery & Primary'), ('full', 'Full K-12')], max_length=20)),
                ('configuration', models.JSONField(help_text='Template configuration JSON')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'schools_template',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, help_text='Optional. 150 characters or fewer.', max_length=150, null=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official school name', max_length=255)),
                ('subdomain', models.SlugField(blank=True, help_text='Optional custom subdomain', null=True, unique=True)),
                ('school_type', models.CharField(choices=[('nursery', 'Nursery Only'), ('primary', 'Primary Only'), ('secondary', 'Secondary Only'), ('combined', 'Nursery & Primary'), ('full', 'Full K-12')], default='primary', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7)),
                ('footer_text', models.TextField(blank=True, default='')),
                ('hide_platform_branding', models.BooleanField(default=True)),
                ('paystack_subaccount_id', models.CharField(blank=True, max_length=128, null=True)),
                ('platform_commission_rate', models.DecimalField(decimal_places=4, default=0.015, max_digits=5)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subdomain_status', models.CharField(choices=[('none', 'No Subdomain'), ('pending', 'Pending Payment'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='none', max_length=20)),
                ('subdomain_expires_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_step', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schools_school',
                'indexes': [models.Index(fields=['subdomain', 'is_active'], name='schools_sch_subdoma_77a109_idx'), models.Index(fields=['subdomain_status', 'subdomain_expires_at'], name='schools_sch_subdoma_773a94_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role display name', max_length=100)),
                ('category', models.CharField(choices=[('administration', 'Administration'), ('academic', 'Academic'), ('student', 'Student'), ('parent', 'Parent'), ('support', 'Support Staff')], max_length=50)),
                ('permissions', models.JSONField(default=list, help_text='List of permission strings')),
                ('is_system_role', models.BooleanField(default=False)),
                ('system_role_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Role description and responsibilities')),
                ('can_manage_roles', models.BooleanField(default=False, help_text='Can create/edit roles')),
                ('can_manage_staff', models.BooleanField(default=False, help_text='Can manage staff members')),
                ('can_manage_students', models.BooleanField(default=False, help_text='Can manage students')),
                ('can_manage_academics', models.BooleanField(default=False, help_text='Can manage academic records')),
                ('can_manage_finances', models.BooleanField(default=False, help_text='Can manage financial records')),
                ('can_view_reports', models.BooleanField(default=False, help_text='Can view reports')),
                ('can_communicate', models.BooleanField(default=False, help_text='Can send communications')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
            options={
                'db_table': 'users_role',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.role')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
            options={
                'db_table': 'users_profile',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='current_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='users.school'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(help_text='Staff identification number', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('volunteer', 'Volunteer')], default='full_time', max_length=20)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('position', models.CharField(help_text='Job title/position', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Department/Section', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('qualifications', models.JSONField(blank=True, default=list, help_text='List of qualifications')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_staff',
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
            options={
                'db_table': 'users_staff_assignment',
            },
        ),
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
            options={
                'db_table': 'users_staff_invitation',
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['school', 'is_system_role'], name='users_role_school__9851af_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['school', 'category'], name='users_role_school__e08c0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'school')},
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['school', 'is_active'], name='users_staff_school__ccd913_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_id'], name='users_staff_staff_i_04dceb_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['email'], name='users_staff_email_442bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['staff', 'is_active'], name='users_staff_staff_i_1f7e4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffassignment',
            unique_together={('staff', 'role')},
        ),
        migrations.AddIndex(
            model_name='staffinvitation',
            index=models.Index(fields=['token', 'status'], name='users_staff_token_c27d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='staffinvitation',
            index=models.Index(fields=['school', 'status'], name='users_staff_school__8421d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffinvitation',
            unique_together={('school', 'email')},
        ),
    ]
