# Generated by Django 5.0.1 on 2025-11-28 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_class_options'),
        ('students', '0005_academicterm_actual_end_date_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AddField(
            model_name='staff',
            name='account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='class_groups',
            field=models.ManyToManyField(blank=True, help_text='Class groups this staff member is assigned to', related_name='assigned_staff', to='students.classgroup'),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='insurance_number',
            field=models.CharField(blank=True, help_text='NHIS or other insurance', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_management',
            field=models.BooleanField(default=False, help_text='Part of school management team'),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_teaching_staff',
            field=models.BooleanField(default=True, help_text='Whether this staff teaches classes'),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_review_date',
            field=models.DateField(blank=True, help_text='Last performance review', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='lga_of_origin',
            field=models.CharField(blank=True, help_text='Local Government Area', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], help_text='Marital status', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='medical_information',
            field=models.TextField(blank=True, help_text='Medical conditions or allergies'),
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(blank=True, default='Nigerian', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='next_of_kin',
            field=models.TextField(blank=True, help_text='Next of kin details'),
        ),
        migrations.AddField(
            model_name='staff',
            name='next_review_date',
            field=models.DateField(blank=True, help_text='Next performance review', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.CharField(blank=True, help_text='Highest qualification (e.g., B.Sc, M.Ed, PhD)', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization',
            field=models.CharField(blank=True, help_text='Area of specialization', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects this staff member teaches', related_name='teaching_staff', to='core.subject'),
        ),
        migrations.AddField(
            model_name='staff',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of teaching/professional experience'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('volunteer', 'Volunteer'), ('temporary', 'Temporary')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualifications',
            field=models.JSONField(blank=True, default=list, help_text='List of qualifications with details'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Staff identification number', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['school', 'department'], name='users_staff_school__a27c27_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['school', 'position'], name='users_staff_school__7270c4_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['date_joined'], name='users_staff_date_jo_00d4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_teaching_staff'], name='users_staff_is_teac_3c8934_idx'),
        ),
    ]
