# Generated by Django 5.0.1 on 2025-11-29 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_staff_options_staff_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True, help_text='Required qualifications and experience')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
            options={
                'db_table': 'users_open_position',
                'indexes': [models.Index(fields=['school', 'is_active'], name='users_open__school__6a2961_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('application_type', models.CharField(choices=[('new_teacher', 'New Teacher (No Experience)'), ('experienced', 'Experienced Teacher'), ('transfer', 'Transfer from Another School')], default='experienced', max_length=20)),
                ('position_applied', models.CharField(help_text='Position being applied for', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('qualification', models.CharField(help_text='Highest qualification', max_length=100)),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization', max_length=200)),
                ('cover_letter', models.TextField(blank=True, help_text='Why you want to join this school')),
                ('resume', models.FileField(blank=True, null=True, upload_to='teacher_resumes/')),
                ('certificates', models.FileField(blank=True, null=True, upload_to='teacher_certificates/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_teacher_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'status'], name='users_teach_school__0d6cc6_idx'), models.Index(fields=['email', 'status'], name='users_teach_email_13bdf8_idx'), models.Index(fields=['created_at'], name='users_teach_created_1ef972_idx')],
            },
        ),
    ]
