# Generated by Django 5.0.1 on 2025-12-02 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teacherapplication_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='allow_external_applications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='allow_staff_applications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='allowed_payment_methods',
            field=models.JSONField(blank=True, default=list, help_text="['bank_transfer', 'paystack', 'cash', 'cheque']"),
        ),
        migrations.AddField(
            model_name='school',
            name='application_deadline_extension_days',
            field=models.PositiveIntegerField(default=7, help_text='Grace period after deadline for special cases'),
        ),
        migrations.AddField(
            model_name='school',
            name='application_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='school',
            name='application_fee_currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='school',
            name='application_fee_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='application_form_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='fee_policies',
            field=models.JSONField(blank=True, default=dict, help_text='School fee policies configuration'),
        ),
        migrations.AddField(
            model_name='school',
            name='scholarship_application_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='scholarship_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='scholarship_max_percentage',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Maximum scholarship percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='school',
            name='staff_children_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount on school fees for staff children', max_digits=5),
        ),
        migrations.AddField(
            model_name='school',
            name='staff_children_max_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum discount amount (0 = unlimited)', max_digits=10),
        ),
        migrations.AddField(
            model_name='school',
            name='staff_children_waive_application_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scholarship_type', models.CharField(choices=[('merit', 'Merit-Based'), ('need', 'Need-Based'), ('sports', 'Sports'), ('arts', 'Arts'), ('staff', 'Staff Discount'), ('external', 'External Sponsorship')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount on fees', max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount discount (alternative to percentage)', max_digits=10)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount', max_digits=10, null=True)),
                ('eligibility_criteria', models.JSONField(blank=True, default=list)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('total_slots', models.PositiveIntegerField(blank=True, null=True)),
                ('slots_taken', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('application_start', models.DateField(blank=True, null=True)),
                ('application_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'db_table': 'schools_scholarship',
                'indexes': [models.Index(fields=['school', 'is_active'], name='schools_sch_school__ac75ca_idx'), models.Index(fields=['scholarship_type'], name='schools_sch_scholar_f612dc_idx')],
            },
        ),
    ]
