# Generated by Django 5.0.1 on 2025-12-16 05:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fee Category',
                'verbose_name_plural': 'Fee Categories',
                'db_table': 'billing_feecategory',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('application', 'Application Fee'), ('school_fees', 'School Fees'), ('acceptance', 'Acceptance Fee'), ('other', 'Other Fees')], default='school_fees', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paystack_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('Partially Paid', 'Partially Paid')], default='draft', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('paystack_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('session', models.CharField(blank=True, help_text='Academic session e.g., 2024/2025', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'billing_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'db_table': 'billing_invoiceitem',
            },
        ),
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('Active', 'Active'), ('Past Due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trialing', max_length=20)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField()),
                ('paystack_subscription_id', models.CharField(blank=True, max_length=100)),
                ('paystack_customer_code', models.CharField(blank=True, max_length=100)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_reminder_sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'School Subscription',
                'verbose_name_plural': 'School Subscriptions',
                'db_table': 'billing_subscription',
            },
        ),
        migrations.CreateModel(
            name='SubdomainPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('basic', 'Basic - Path URL'), ('standard', 'Standard - Custom Subdomain'), ('premium', 'Premium - Full Branding')], default='basic', max_length=20)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_students', models.IntegerField(default=100)),
                ('max_staff', models.IntegerField(default=10)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('popular', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'billing_plan',
                'ordering': ['order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paystack_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('school_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('failed', 'Reversed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('metadata', models.JSONField(default=dict)),
                ('paystack_response', models.JSONField(default=dict, help_text='Raw response from Paystack')),
                ('payment_method', models.CharField(choices=[('paystack', 'Paystack'), ('cash', 'Cash'), ('transfer', 'Transfer'), ('waiver', 'Waiver')], default='paystack', max_length=20)),
                ('channel', models.CharField(blank=True, help_text='Payment channel: card, bank, etc.', max_length=50)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'billing_transaction',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('application', 'Application Fee'), ('registration', 'Registration Fee'), ('pta', 'PTA Levy'), ('development', 'Development Levy'), ('medical', 'Medical Fee'), ('sports', 'Sports Fee'), ('textbook', 'Textbook Fee'), ('uniform', 'Uniform Fee'), ('boarding', 'Boarding Fee'), ('transport', 'Transport Fee'), ('caution', 'Caution Fee'), ('other', 'Other Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_required', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('applicable_levels', models.JSONField(default=list, help_text='Levels this fee applies to')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_government_approved', models.BooleanField(default=False)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='VAT percentage if applicable', max_digits=5)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.feecategory')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'db_table': 'billing_feestructure',
                'ordering': ['category__order', 'fee_type', 'amount'],
            },
        ),
    ]
