# Generated by Django 5.0.1 on 2025-11-22 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('students', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='users.school'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.parent'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.school'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='students.student'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.academicterm'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.feestructure'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.school'),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.subdomainplan'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.invoice'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['school', 'is_active'], name='billing_fee_school__d67b71_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['fee_type', 'is_active'], name='billing_fee_fee_typ_6cfa0d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='billing_inv_invoice_70511c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['school', 'status'], name='billing_inv_school__69702f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['parent', 'status'], name='billing_inv_parent__37ee12_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='billing_inv_due_dat_7d5547_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['paystack_reference'], name='billing_tra_paystac_1f84a0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['invoice', 'status'], name='billing_tra_invoice_b03369_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['initiated_at'], name='billing_tra_initiat_3e6888_idx'),
        ),
    ]
