# Generated by Django 5.0.1 on 2025-12-16 05:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary School'), ('jss', 'Junior Secondary School'), ('sss', 'Senior Secondary School')], max_length=20)),
                ('name', models.CharField(help_text="Level name (e.g., 'Primary 1', 'JSS 2')", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order within level')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'students_education_level',
                'ordering': ['school', 'level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_type', models.CharField(choices=[('new', 'New Student'), ('continuing', 'Continuing Student'), ('transfer', 'Transfer Student')], default='continuing', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'students_enrollment',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian'), ('sibling', 'Sibling'), ('other', 'Other')], default='parent', max_length=50)),
                ('is_staff_child', models.BooleanField(default=False, help_text="Is this a staff member's child?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'students_parent',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score out of maximum', max_digits=5)),
                ('maximum_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('assessment_type', models.CharField(choices=[('test', 'Test'), ('exam', 'Exam'), ('assignment', 'Assignment'), ('project', 'Project'), ('quiz', 'Quiz'), ('practical', 'Practical')], help_text='Type of assessment', max_length=50)),
                ('assessment_name', models.CharField(blank=True, help_text="e.g., 'First Term Exam', 'Mid-term Test'", max_length=100)),
                ('assessment_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'db_table': 'students_score',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Undisclosed')], default='U', max_length=1)),
                ('date_of_birth', models.DateField()),
                ('admission_status', models.CharField(choices=[('pending', 'Applied/Pending'), ('under_review', 'Under Review'), ('approved', 'Accepted'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('is_staff_child', models.BooleanField(default=False, help_text="Is this a staff member's child?")),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('previous_class', models.CharField(blank=True, max_length=100)),
                ('application_notes', models.TextField(blank=True)),
                ('application_date', models.DateTimeField(blank=True, null=True)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, default='Nigerian', max_length=100)),
                ('state_of_origin', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students_student',
                'ordering': ['admission_number'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], max_length=10)),
                ('academic_year', models.CharField(help_text='e.g., 2024/2025', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, help_text='Actual end date if extended', null=True)),
                ('planned_weeks', models.PositiveIntegerField(default=12, help_text='Planned duration in weeks')),
                ('actual_weeks', models.PositiveIntegerField(blank=True, help_text='Actual duration in weeks', null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Closed'), ('extended', 'Extended')], default='upcoming', max_length=15)),
                ('is_active', models.BooleanField(default=False)),
                ('mid_term_break_start', models.DateField(blank=True, null=True)),
                ('mid_term_break_end', models.DateField(blank=True, null=True)),
                ('closure_start', models.DateField(blank=True, help_text='Unexpected closure start (strike, pandemic)', null=True)),
                ('closure_end', models.DateField(blank=True, help_text='Unexpected closure end', null=True)),
                ('closure_reason', models.TextField(blank=True, help_text='Reason for closure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'db_table': 'students_academic_term',
                'ordering': ['-academic_year', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused Absence'), ('sick', 'Sick Leave'), ('other', 'Other')], default='present', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('time_in', models.TimeField(blank=True, help_text='Time student arrived', null=True)),
                ('time_out', models.TimeField(blank=True, help_text='Time student left', null=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.academicterm')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'students_attendance',
                'ordering': ['-date', 'student'],
            },
        ),
    ]
