# Generated by Django 5.0.1 on 2025-12-16 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('students', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.academicterm'),
        ),
        migrations.AddField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='parent',
            name='staff_member',
            field=models.ForeignKey(blank=True, help_text='Staff member who is the parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_parent', to='users.staff'),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='score',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, help_text="Student's current academic class assignment", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.class'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.educationlevel'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['school', 'is_active'], name='students_ac_school__c94aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['school', 'status'], name='students_ac_school__ced188_idx'),
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['start_date', 'end_date'], name='students_ac_start_d_10949c_idx'),
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['academic_year'], name='students_ac_academi_8df928_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('school', 'academic_year', 'term')},
        ),
        migrations.AddIndex(
            model_name='educationlevel',
            index=models.Index(fields=['school', 'level'], name='students_ed_school__0d144c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='educationlevel',
            unique_together={('school', 'level', 'name')},
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['school', 'email'], name='students_pa_school__fe27e7_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['school', 'phone_number'], name='students_pa_school__0b08d9_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['is_staff_child'], name='students_pa_is_staf_68a711_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['staff_member'], name='students_pa_staff_m_798a1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('school', 'email')},
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['enrollment', 'subject'], name='students_sc_enrollm_e004f3_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['assessment_date'], name='students_sc_assessm_222950_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['subject'], name='students_sc_subject_c0a7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['assessment_type'], name='students_sc_assessm_92051a_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'admission_number'], name='students_st_school__252cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'parent'], name='students_st_school__300857_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'education_level'], name='students_st_school__1491fe_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'is_active'], name='students_st_school__3f378d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'current_class'], name='students_st_school__8615d9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'admission_status'], name='students_st_school__c31eec_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'is_staff_child'], name='students_st_school__e9c76f_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['date_of_birth'], name='students_st_date_of_a50842_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['first_name', 'last_name'], name='students_st_first_n_e9466d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'is_active'], name='students_en_student_39d90d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['academic_term', 'is_active'], name='students_en_academi_de8fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrollment_type'], name='students_en_enrollm_5bd1a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_term')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='students_at_student_57d285_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['academic_term', 'date'], name='students_at_academi_5c5b16_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='students_at_status_90671f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='students_at_date_895989_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
