# Generated by Django 5.0.1 on 2025-11-22 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicterm'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_of', to='users.profile'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='teaching_classes', to='users.profile'),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.educationlevel'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicterm'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classgroup'),
        ),
        migrations.AddField(
            model_name='parent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='score',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='score',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
        migrations.AddField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classgroup'),
        ),
        migrations.AddField(
            model_name='student',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.educationlevel'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('school', 'academic_year', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='educationlevel',
            unique_together={('school', 'level', 'name')},
        ),
        migrations.AddIndex(
            model_name='classgroup',
            index=models.Index(fields=['school', 'education_level'], name='students_cl_school__027cf7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['school', 'email'], name='students_pa_school__fe27e7_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['school', 'phone_number'], name='students_pa_school__0b08d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('school', 'email')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'admission_number'], name='students_st_school__252cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'parent'], name='students_st_school__300857_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'education_level'], name='students_st_school__1491fe_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'is_active'], name='students_st_school__3f378d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'is_active'], name='students_en_student_39d90d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['class_group', 'academic_term'], name='students_en_class_g_b9eb58_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_term')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='students_at_student_57d285_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['academic_term', 'date'], name='students_at_academi_5c5b16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'is_active'], name='students_su_school__a4ffb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['enrollment', 'subject'], name='students_sc_enrollm_e004f3_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['assessment_date'], name='students_sc_assessm_222950_idx'),
        ),
    ]
