# Generated by Django 5.0.1 on 2025-11-26 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_class_options'),
        ('students', '0003_alter_score_subject_delete_subject'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['admission_number']},
        ),
        migrations.AddField(
            model_name='student',
            name='current_class',
            field=models.ForeignKey(blank=True, help_text="Student's current class assignment", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.class'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'current_class'], name='students_st_school__8615d9_idx'),
        ),
    ]
