# Generated by Django 5.0.1 on 2025-11-28 01:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options_student_current_class_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='actual_end_date',
            field=models.DateField(blank=True, help_text='Actual end date if extended', null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='actual_weeks',
            field=models.PositiveIntegerField(blank=True, help_text='Actual duration in weeks', null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='closure_end',
            field=models.DateField(blank=True, help_text='Unexpected closure end', null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='closure_reason',
            field=models.TextField(blank=True, help_text='Reason for closure'),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='closure_start',
            field=models.DateField(blank=True, help_text='Unexpected closure start (strike, pandemic)', null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='mid_term_break_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='mid_term_break_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='planned_weeks',
            field=models.PositiveIntegerField(default=12, help_text='Planned duration in weeks'),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed'), ('extended', 'Extended')], default='upcoming', max_length=15),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['school', 'is_active'], name='students_ac_school__c94aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['school', 'status'], name='students_ac_school__ced188_idx'),
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['start_date', 'end_date'], name='students_ac_start_d_10949c_idx'),
        ),
    ]
