# Generated by Django 5.0.1 on 2025-12-16 05:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2024/2025', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'core_academic_year',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('jss', 'Junior Secondary'), ('sss', 'Senior Secondary'), ('special', 'Special Needs')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Class Category',
                'verbose_name_plural': 'Class Categories',
                'db_table': 'core_class_category',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassCreationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(choices=[('nursery', 'Nursery Only'), ('primary', 'Primary Only'), ('secondary', 'Secondary Only'), ('combined', 'Nursery & Primary'), ('full', 'Full K-12')], max_length=20)),
                ('template_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField(help_text='Template configuration for classes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class Template',
                'verbose_name_plural': 'Class Templates',
                'db_table': 'core_class_template',
                'ordering': ['template_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head', 'Head Monitor'), ('assistant', 'Assistant Monitor'), ('prefect', 'Prefect'), ('captain', 'Captain'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer')], max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('responsibilities', models.TextField(help_text='List of monitor responsibilities')),
                ('position', models.CharField(max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Class Monitor',
                'verbose_name_plural': 'Class Monitors',
                'db_table': 'core_class_monitor',
                'ordering': ['class_instance', 'role', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('periods_per_week', models.IntegerField(default=5, help_text='Number of periods per week')),
                ('elective_group', models.CharField(blank=True, help_text='Elective group name', max_length=50)),
            ],
            options={
                'verbose_name': 'Class Subject',
                'verbose_name_plural': 'Class Subjects',
                'db_table': 'core_class_subject',
                'ordering': ['display_order', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official school name', max_length=255)),
                ('subdomain', models.SlugField(blank=True, help_text='Optional custom subdomain', null=True, unique=True)),
                ('school_type', models.CharField(choices=[('nursery', 'Nursery Only'), ('primary', 'Primary Only'), ('secondary', 'Secondary Only'), ('combined', 'Nursery & Primary'), ('full', 'Full K-12')], default='primary', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7)),
                ('footer_text', models.TextField(blank=True, default='')),
                ('hide_platform_branding', models.BooleanField(default=True)),
                ('paystack_subaccount_id', models.CharField(blank=True, max_length=128, null=True)),
                ('platform_commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.015'), max_digits=5)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subdomain_status', models.CharField(choices=[('none', 'No Subdomain'), ('pending', 'Pending Payment'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='none', max_length=20)),
                ('subdomain_expires_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('onboarding_step', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_policies', models.JSONField(blank=True, default=dict, help_text='School fee policies configuration')),
                ('application_fee_required', models.BooleanField(default=True)),
                ('application_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('application_fee_currency', models.CharField(default='NGN', max_length=3)),
                ('staff_children_waive_application_fee', models.BooleanField(default=False)),
                ('staff_children_discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentage discount on school fees for staff children', max_digits=5)),
                ('staff_children_max_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Maximum discount amount (0 = unlimited)', max_digits=10)),
                ('scholarship_enabled', models.BooleanField(default=False)),
                ('scholarship_application_required', models.BooleanField(default=False)),
                ('scholarship_max_percentage', models.DecimalField(decimal_places=2, default=Decimal('100'), help_text='Maximum scholarship percentage', max_digits=5)),
                ('allowed_payment_methods', models.JSONField(blank=True, default=list, help_text="['bank_transfer', 'paystack', 'cash', 'cheque']")),
                ('application_form_enabled', models.BooleanField(default=True)),
                ('allow_staff_applications', models.BooleanField(default=True)),
                ('allow_external_applications', models.BooleanField(default=True)),
                ('application_deadline_extension_days', models.PositiveIntegerField(default=7, help_text='Grace period after deadline for special cases')),
            ],
            options={
                'db_table': 'schools_school',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Subject code, e.g., MATH, ENG, BIO', max_length=20)),
                ('category', models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective Subject'), ('extracurricular', 'Extracurricular'), ('technical', 'Technical/Vocational'), ('arts', 'Arts & Music'), ('sports', 'Sports & Physical Education')], default='core', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('honors', 'Honors')], default='basic', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.JSONField(default=list, help_text='Learning objectives')),
                ('max_score', models.IntegerField(default=100, help_text='Maximum score for this subject')),
                ('pass_score', models.IntegerField(default=40, help_text='Minimum passing score')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'core_subject',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_type', models.CharField(choices=[('academic', 'Academic Class'), ('stream', 'Stream/Group'), ('club', 'Club/Activity'), ('tutorial', 'Tutorial Group')], default='academic', max_length=20)),
                ('max_students', models.IntegerField(default=40)),
                ('current_strength', models.IntegerField(default=0, editable=False)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('is_graduated', models.BooleanField(default=False)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.academicyear')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'core_class',
                'ordering': ['category__display_order', 'name'],
            },
        ),
    ]
