# Generated by Django 5.0.1 on 2025-11-23 20:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCreationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(choices=[('nursery', 'Nursery Only'), ('primary', 'Primary Only'), ('secondary', 'Secondary Only'), ('combined', 'Nursery & Primary'), ('full', 'Full K-12')], max_length=20)),
                ('template_name', models.CharField(max_length=100)),
                ('configuration', models.JSONField(help_text='Template configuration for classes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_class_template',
            },
        ),
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('jss', 'Junior Secondary'), ('sss', 'Senior Secondary'), ('special', 'Special Needs')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
            options={
                'db_table': 'core_class_category',
                'ordering': ['display_order', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., SSS 1A, Primary 3B', max_length=100)),
                ('code', models.CharField(help_text='Unique class code', max_length=20, unique=True)),
                ('max_students', models.IntegerField(default=40)),
                ('current_strength', models.IntegerField(default=0)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('academic_session', models.CharField(blank=True, help_text='e.g., 2024/2025', max_length=50)),
                ('is_graduated', models.BooleanField(default=False)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_form_master', models.ForeignKey(blank=True, help_text='Assistant form master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_form_master_classes', to='users.staff')),
                ('form_master', models.ForeignKey(blank=True, help_text='Teacher responsible for this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_master_classes', to='users.staff')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classcategory')),
            ],
            options={
                'db_table': 'core_class',
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head', 'Head Monitor'), ('assistant', 'Assistant Monitor'), ('prefect', 'Prefect'), ('captain', 'Captain')], max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('responsibilities', models.JSONField(default=list, help_text='List of monitor responsibilities')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'core_class_monitor',
                'ordering': ['class_instance', 'role', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Subject code, e.g., MATH, ENG, BIO', max_length=20)),
                ('category', models.CharField(choices=[('core', 'Core Subject'), ('elective', 'Elective Subject'), ('extracurricular', 'Extracurricular'), ('technical', 'Technical/Vocational')], default='core', max_length=20)),
                ('difficulty_level', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.JSONField(default=list, help_text='Learning objectives')),
                ('max_score', models.IntegerField(default=100, help_text='Maximum score for this subject')),
                ('pass_score', models.IntegerField(default=40, help_text='Minimum passing score')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Required subjects', to='core.subject')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
            options={
                'db_table': 'core_subject',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
            options={
                'db_table': 'core_class_subject',
                'ordering': ['display_order', 'subject__name'],
            },
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'is_active'], name='core_class_school__981621_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['form_master', 'is_active'], name='core_class_form_ma_b8de1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classmonitor',
            unique_together={('class_instance', 'student', 'role')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'is_active'], name='core_subjec_school__04e894_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['category', 'difficulty_level'], name='core_subjec_categor_41b981_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_instance', 'subject')},
        ),
    ]
