# Generated by Django 5.0.1 on 2025-11-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['category__display_order', 'name'], 'verbose_name_plural': 'Classes'},
        ),
    ]
