# Generated by Django 5.0.1 on 2025-12-16 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='assistant_form_master',
            field=models.ForeignKey(blank=True, help_text='Assistant form master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_form_master_classes', to='users.staff'),
        ),
        migrations.AddField(
            model_name='class',
            name='education_level',
            field=models.ForeignKey(blank=True, help_text='Education level for this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='students.educationlevel'),
        ),
        migrations.AddField(
            model_name='class',
            name='form_master',
            field=models.ForeignKey(blank=True, help_text='Teacher responsible for this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_master_classes', to='users.staff'),
        ),
        migrations.AddField(
            model_name='class',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='core.classcategory'),
        ),
        migrations.AddIndex(
            model_name='classcreationtemplate',
            index=models.Index(fields=['school_type', 'is_active'], name='core_class__school__e331d4_idx'),
        ),
        migrations.AddField(
            model_name='classmonitor',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classmonitor',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='core.class'),
        ),
        migrations.AddField(
            model_name='classmonitor',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_positions', to='students.student'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_offered', to='core.class'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_assignments', to='users.staff'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['subdomain', 'is_active'], name='schools_sch_subdoma_77a109_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['subdomain_status', 'subdomain_expires_at'], name='schools_sch_subdoma_773a94_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='schools_sch_name_5d0cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['contact_email'], name='schools_sch_contact_900985_idx'),
        ),
        migrations.AddField(
            model_name='classcategory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_categories', to='core.school'),
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.school'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.school'),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Required subjects', to='core.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.school'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_offerings', to='core.subject'),
        ),
        migrations.AddIndex(
            model_name='classmonitor',
            index=models.Index(fields=['class_instance', 'is_active'], name='core_class__class_i_fd0c06_idx'),
        ),
        migrations.AddIndex(
            model_name='classmonitor',
            index=models.Index(fields=['student', 'is_active'], name='core_class__student_ab30fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classmonitor',
            unique_together={('class_instance', 'student', 'role')},
        ),
        migrations.AddIndex(
            model_name='classcategory',
            index=models.Index(fields=['school', 'is_active'], name='core_class__school__232c07_idx'),
        ),
        migrations.AddIndex(
            model_name='classcategory',
            index=models.Index(fields=['section'], name='core_class__section_e174d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classcategory',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'is_active'], name='core_class_school__981621_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['form_master', 'is_active'], name='core_class_form_ma_b8de1f_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['academic_year', 'class_type'], name='core_class_academi_66e19e_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'academic_year'], name='core_class_school__ccf40a_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['education_level'], name='core_class_educati_bed669_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['name'], name='core_class_name_d2e40d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'school', 'academic_year', 'class_type')},
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['school', 'is_current'], name='core_academ_school__241866_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['start_date', 'end_date'], name='core_academ_start_d_4e411c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'name')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'is_active'], name='core_subjec_school__04e894_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['category', 'difficulty_level'], name='core_subjec_categor_41b981_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='core_subjec_code_91b858_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['display_order'], name='core_subjec_display_3087fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'code')},
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['class_instance', 'is_compulsory'], name='core_class__class_i_f75281_idx'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['teacher'], name='core_class__teacher_51dfc9_idx'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['elective_group'], name='core_class__electiv_2668fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('class_instance', 'subject')},
        ),
    ]
