# Generated by Django 5.0.1 on 2025-12-16 05:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('admission_type', models.CharField(choices=[('regular', 'Regular Admission'), ('transfer', 'Transfer Student'), ('special', 'Special Consideration')], default='regular', max_length=20)),
                ('offer_expires', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_notes', models.TextField(blank=True, help_text="Parent's acceptance notes")),
                ('requires_acceptance_fee', models.BooleanField(default=False)),
                ('acceptance_fee_paid', models.BooleanField(default=False)),
                ('acceptance_fee_deadline', models.DateTimeField(blank=True, null=True)),
                ('admission_letter_sent', models.BooleanField(default=False)),
                ('admission_letter_sent_at', models.DateTimeField(blank=True, null=True)),
                ('admission_letter_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('print', 'Printed'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('conditions', models.JSONField(default=list, help_text='Admission conditions to be met')),
                ('required_documents_submitted', models.BooleanField(default=False)),
                ('documents_verified', models.BooleanField(default=False)),
                ('enrollment_deadline', models.DateTimeField(blank=True, null=True)),
                ('enrollment_completed', models.BooleanField(default=False)),
                ('enrollment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'db_table': 'admissions_admission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_staff_child', models.BooleanField(default=False, help_text='Is this a staff child application?')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('data', models.JSONField(default=dict, help_text='Application form data')),
                ('documents', models.JSONField(default=list, help_text='Uploaded documents')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('status_history', models.JSONField(default=list, help_text='Status change history')),
                ('application_fee_paid', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('previous_school_info', models.JSONField(default=dict, help_text='Previous school information')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'admissions_application',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free', models.BooleanField(default=True)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('position_applied', models.CharField(help_text='Position/Class being applied for', max_length=100)),
                ('has_acceptance_fee', models.BooleanField(default=False)),
                ('acceptance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fields', models.JSONField(default=list, help_text='Custom form fields configuration')),
                ('required_documents', models.JSONField(default=list, help_text='List of required documents')),
                ('eligibility_criteria', models.JSONField(default=list, help_text='Eligibility requirements')),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_date', models.DateTimeField()),
                ('academic_session', models.CharField(help_text='e.g., 2024/2025', max_length=20)),
                ('available_class_ids', models.JSONField(default=list, help_text='List of Class IDs accepting applications')),
                ('max_applications', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited', null=True)),
                ('applications_so_far', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Form',
                'verbose_name_plural': 'Application Forms',
                'db_table': 'admissions_applicationform',
                'ordering': ['-created_at'],
            },
        ),
    ]
