# Generated by Django 5.0.1 on 2025-11-22 08:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('offer_expires', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('requires_acceptance_fee', models.BooleanField(default=False)),
                ('acceptance_fee_paid', models.BooleanField(default=False)),
                ('admission_letter_sent', models.BooleanField(default=False)),
                ('admission_letter_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'db_table': 'admissions_admission',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('data', models.JSONField(default=dict, help_text='Application form data')),
                ('documents', models.JSONField(default=list, help_text='Uploaded documents')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='submitted', max_length=20)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('application_fee_paid', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('previous_school_info', models.JSONField(default=dict, help_text='Previous school information')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'admissions_application',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('application_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_free', models.BooleanField(default=True)),
                ('has_acceptance_fee', models.BooleanField(default=False)),
                ('acceptance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fields', models.JSONField(default=list, help_text='Custom form fields configuration')),
                ('required_documents', models.JSONField(default=list, help_text='List of required documents')),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_date', models.DateTimeField()),
                ('academic_session', models.CharField(help_text='e.g., 2024/2025', max_length=20)),
                ('available_classes', models.JSONField(default=list, help_text='Classes accepting applications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Form',
                'verbose_name_plural': 'Application Forms',
                'db_table': 'admissions_applicationform',
            },
        ),
    ]
