# Generated by Django 5.0.1 on 2025-11-22 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_initial'),
        ('billing', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='offered_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_offers', to='students.classgroup'),
        ),
        migrations.AddField(
            model_name='admission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='students.student'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_fee_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='application',
            name='applied_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.classgroup'),
        ),
    ]
