# Generated by Django 5.0.1 on 2025-12-16 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_initial'),
        ('billing', '0002_initial'),
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admissions', to='users.staff'),
        ),
        migrations.AddField(
            model_name='admission',
            name='offered_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_offers', to='core.class'),
        ),
        migrations.AddField(
            model_name='admission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='students.student'),
        ),
        migrations.AddField(
            model_name='application',
            name='application_fee_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='application',
            name='applied_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.class'),
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='users.staff'),
        ),
        migrations.AddField(
            model_name='application',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.parent'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student'),
        ),
        migrations.AddField(
            model_name='admission',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='admissions.application'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_forms', to='core.school'),
        ),
        migrations.AddField(
            model_name='application',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.applicationform'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['admission_number'], name='admissions__admissi_9dcc3e_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['application'], name='admissions__applica_a33070_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['student'], name='admissions__student_293ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['offered_class'], name='admissions__offered_3daae8_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['offer_expires'], name='admissions__offer_e_92e33e_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['accepted'], name='admissions__accepte_36833e_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['enrollment_deadline'], name='admissions__enrollm_57119c_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['acceptance_fee_deadline'], name='admissions__accepta_a98e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationform',
            index=models.Index(fields=['school', 'status'], name='admissions__school__292f53_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationform',
            index=models.Index(fields=['open_date', 'close_date'], name='admissions__open_da_a9122b_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationform',
            index=models.Index(fields=['slug'], name='admissions__slug_43dc34_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationform',
            index=models.Index(fields=['academic_session'], name='admissions__academi_da9098_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_number'], name='admissions__applica_7574f8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['form', 'status'], name='admissions__form_id_09977a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['parent', 'status'], name='admissions__parent__389466_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['student', 'status'], name='admissions__student_6d7b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['submitted_at'], name='admissions__submitt_f17493_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['priority'], name='admissions__priorit_184d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_staff_child'], name='admissions__is_staf_3d52f0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_class'], name='admissions__applied_75e963_idx'),
        ),
    ]
