# Generated by Django 5.0.1 on 2025-11-22 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0003_initial'),
        ('students', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='users.staff'),
        ),
        migrations.AddField(
            model_name='application',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.parent'),
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student'),
        ),
        migrations.AddField(
            model_name='admission',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='admissions.application'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_forms', to='users.school'),
        ),
        migrations.AddField(
            model_name='application',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.applicationform'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['admission_number'], name='admissions__admissi_9dcc3e_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['application'], name='admissions__applica_a33070_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationform',
            index=models.Index(fields=['school', 'status'], name='admissions__school__292f53_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationform',
            index=models.Index(fields=['open_date', 'close_date'], name='admissions__open_da_a9122b_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_number'], name='admissions__applica_7574f8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['form', 'status'], name='admissions__form_id_09977a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['parent', 'status'], name='admissions__parent__389466_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['submitted_at'], name='admissions__submitt_f17493_idx'),
        ),
    ]
