# Generated by Django 5.0.1 on 2025-11-27 12:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_initial'),
        ('billing', '0002_initial'),
        ('students', '0004_alter_student_options_student_current_class_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admission', 'verbose_name_plural': 'Admissions'},
        ),
        migrations.AlterModelOptions(
            name='applicationform',
            options={'ordering': ['-created_at'], 'verbose_name': 'Application Form', 'verbose_name_plural': 'Application Forms'},
        ),
        migrations.AddField(
            model_name='admission',
            name='acceptance_fee_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='acceptance_notes',
            field=models.TextField(blank=True, help_text="Parent's acceptance notes"),
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_letter_method',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('print', 'Printed'), ('whatsapp', 'WhatsApp')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_type',
            field=models.CharField(choices=[('regular', 'Regular Admission'), ('transfer', 'Transfer Student'), ('special', 'Special Consideration')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='conditions',
            field=models.JSONField(default=list, help_text='Admission conditions to be met'),
        ),
        migrations.AddField(
            model_name='admission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admissions', to='users.staff'),
        ),
        migrations.AddField(
            model_name='admission',
            name='documents_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='enrollment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='enrollment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='enrollment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='required_documents_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='application',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='public_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status_history',
            field=models.JSONField(default=list, help_text='Status change history'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='applications_so_far',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='eligibility_criteria',
            field=models.JSONField(default=list, help_text='Eligibility requirements'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='max_applications',
            field=models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited', null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['student'], name='admissions__student_293ca8_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['offer_expires'], name='admissions__offer_e_92e33e_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['accepted'], name='admissions__accepte_36833e_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['enrollment_deadline'], name='admissions__enrollm_57119c_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['priority'], name='admissions__priorit_184d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationform',
            index=models.Index(fields=['slug'], name='admissions__slug_43dc34_idx'),
        ),
    ]
