# Generated by Django 5.0.1 on 2025-12-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_alter_admission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20),
        ),
    ]
