# Generated by Django 5.0.1 on 2025-12-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('single', 'Single Session'), ('double', 'Double Session')], default='single', max_length=10)),
                ('student_marking_enabled', models.BooleanField(default=True)),
                ('auto_mark_absent', models.BooleanField(default=True)),
                ('late_threshold_minutes', models.IntegerField(default=30)),
                ('early_departure_minutes', models.IntegerField(default=60)),
                ('teacher_attendance_enabled', models.BooleanField(default=True)),
                ('teacher_signin_required', models.BooleanField(default=True)),
                ('teacher_late_threshold', models.IntegerField(default=15)),
                ('school_start_time', models.TimeField(default='08:00:00')),
                ('school_end_time', models.TimeField(default='14:00:00')),
                ('break_start_time', models.TimeField(blank=True, null=True)),
                ('break_end_time', models.TimeField(blank=True, null=True)),
                ('send_absent_notifications', models.BooleanField(default=True)),
                ('notify_on_late_teachers', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Attendance Configuration',
                'verbose_name_plural': 'Attendance Configurations',
                'db_table': 'attendance_config',
            },
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_days', models.IntegerField(default=0)),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('days_late', models.IntegerField(default=0)),
                ('days_excused', models.IntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('punctuality_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Attendance Summary',
                'verbose_name_plural': 'Attendance Summaries',
                'db_table': 'attendance_summary',
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused Absence'), ('sick', 'Sick Leave'), ('other', 'Other')], default='present', max_length=10)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('is_late', models.BooleanField(default=False)),
                ('early_departure', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendance Records',
                'db_table': 'attendance_student',
                'ordering': ['-date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('leave', 'On Leave'), ('other', 'Other')], default='present', max_length=10)),
                ('sign_in_time', models.DateTimeField(blank=True, null=True)),
                ('sign_out_time', models.DateTimeField(blank=True, null=True)),
                ('sign_in_location', models.CharField(blank=True, max_length=255)),
                ('sign_out_location', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('is_late', models.BooleanField(default=False)),
                ('auto_signed_out', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teacher Attendance',
                'verbose_name_plural': 'Teacher Attendance Records',
                'db_table': 'attendance_teacher',
                'ordering': ['-date', 'staff'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_work_days', models.IntegerField(default=0)),
                ('days_present', models.IntegerField(default=0)),
                ('days_absent', models.IntegerField(default=0)),
                ('days_late', models.IntegerField(default=0)),
                ('average_work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('punctuality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_performance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('classes_taught', models.IntegerField(default=0)),
                ('extra_duties', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Teacher Performance',
                'verbose_name_plural': 'Teacher Performance Records',
                'db_table': 'attendance_teacher_performance',
            },
        ),
    ]
