# Generated by Django 5.0.1 on 2025-11-22 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceconfig',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_config', to='users.school'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicterm'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicterm'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_student_attendance', to='users.profile'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicterm'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_teacher_attendance', to='users.profile'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.staff'),
        ),
        migrations.AddField(
            model_name='teacherperformance',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicterm'),
        ),
        migrations.AddField(
            model_name='teacherperformance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='users.staff'),
        ),
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['student', 'start_date'], name='attendance__student_08cb20_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['academic_term', 'period_type'], name='attendance__academi_7f9f30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('student', 'academic_term', 'period_type', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['student', 'date'], name='attendance__student_d9a323_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['academic_term', 'date'], name='attendance__academi_1e7706_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date', 'status'], name='attendance__date_2d0553_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'date')},
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['staff', 'date'], name='attendance__staff_i_80a869_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['academic_term', 'date'], name='attendance__academi_c52bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['date', 'status'], name='attendance__date_1dee69_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['sign_in_time'], name='attendance__sign_in_61b848_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('staff', 'date')},
        ),
        migrations.AddIndex(
            model_name='teacherperformance',
            index=models.Index(fields=['staff', 'start_date'], name='attendance__staff_i_5e0596_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherperformance',
            index=models.Index(fields=['academic_term', 'period_type'], name='attendance__academi_782f11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherperformance',
            unique_together={('staff', 'academic_term', 'period_type', 'start_date')},
        ),
    ]
