# Generated by Django 5.0.1 on 2025-11-24 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('core', '0001_initial'),
        ('students', '0003_alter_score_subject_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_students', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('absent_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('excused_count', models.IntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicterm')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='core.class')),
            ],
            options={
                'verbose_name': 'Class Attendance Summary',
                'verbose_name_plural': 'Class Attendance Summaries',
                'db_table': 'attendance_class_summary',
                'ordering': ['-date', 'class_group'],
                'indexes': [models.Index(fields=['class_group', 'date'], name='attendance__class_g_88b948_idx'), models.Index(fields=['date', 'attendance_rate'], name='attendance__date_daab5f_idx')],
                'unique_together': {('class_group', 'date')},
            },
        ),
    ]
