# Generated by Django 5.0.1 on 2025-12-16 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicterm'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='students.student'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='academic_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.academicterm'),
        ),
    ]
